In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.csv")
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [3]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [4]:
roi = ["BsmtFullBath","BsmtHalfBath","FullBath","HalfBath","BedroomAbvGr","LotArea"]

X = df[roi]
X.head()

BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  LotArea
0             1             0         2         1             3     8450
1             0             1         2         0             3     9600
2             1             0         2         1             3    11250
3             1             0         1         0             3     9550
4             1             0         2         1             4    14260

In [5]:
Y = df["SalePrice"]
Y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [6]:
print(np.shape(X),np.shape(Y))

(1460, 6) (1460,)


In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error ,r2_score

In [32]:
scale = StandardScaler()
X= scale.fit_transform(X)

print(X[:5])

[[ 1.10781015 -0.24106104  0.78974052  1.22758538  0.16377912 -0.20714171]
 [-0.81996437  3.94880935  0.78974052 -0.76162067  0.16377912 -0.09188637]
 [ 1.10781015 -0.24106104  0.78974052  1.22758538  0.16377912  0.07347998]
 [ 1.10781015 -0.24106104 -1.02604084 -0.76162067  0.16377912 -0.09689747]
 [ 1.10781015 -0.24106104  0.78974052  1.22758538  1.39002276  0.37514829]]


In [33]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [34]:
print(f"m vector :{model.coef_}")
print(f"c vector :{model.intercept_}")

m vector :[19163.45665675  3766.58520945 43891.21527655 18288.21186882
 -5527.0868099  12610.5606925 ]
c vector :180921.19589041095


In [38]:
y_pred = model.predict(X)
mean_squared_error(Y,y_pred)
r2_score(Y,y_pred)

0.45948985964343114